(library
 (name bonsai_web_ui_partial_render_table_computation_report)
 (libraries bonsai bonsai.perf_shared bonsai_web bonsai_web_test
   bonsai_web_ui_element_size_hooks bonsai_web_ui_partial_render_table_ansi
   bonsai_web_ui_partial_render_table_configs_for_testing
   bonsai_web_ui_partial_render_table_protocol core incr_map.collate
   js_of_ocaml incr_map.erase_key virtual_dom.ui_effect
   virtual_dom.vdom_test_helpers)
 (inline_tests (flags -drop-tag no-js -drop-tag 64-bits-only -drop-tag no-wasm) (modes js wasm))
 (preprocess
  (pps ppx_jane bonsai.ppx_bonsai)))
