(library
 (name bonsai_web_ui_form_test)
 (public_name bonsai_web_components.form_test)
 (inline_tests (flags -drop-tag no-js -drop-tag 64-bits-only -drop-tag no-wasm) (modes js wasm))
 (libraries bonsai_web bonsai_web.proc bonsai_web_test bonsai_web_ui_file
   bonsai_web_ui_form bonsai_web_ui_query_box core
   expect_test_helpers_core.expect_test_helpers_base
   patdiff.expect_test_patdiff js_of_ocaml virtual_dom.ui_effect)
 (preprocess
  (pps ppx_jane js_of_ocaml-ppx bonsai.ppx_bonsai)))
